### ISSUE TITLE
How can set default selected marker?

### ISSUE THREAD

**Issue by droidwithme** [Bhoomika06/Styled-Map-Pager#1]
I am trying to use your repo, but i wants to set selected one default marker. How to do that? @Bhoomika06

**Comment by Bhoomika06** [comment]
You can achieve it by calling addSelectedCustomPin(arrPosition). Need to pass indexPosition of Array which you are using here. Foe Example, addSelectedCustomPin(0). So you can see default marker on Your map at 0th indexed Location.

**Comment by droidwithme** [comment]
so in `CustomMap` or where?

**Comment by droidwithme** [comment]
Great! Got it.

**Comment by Bhoomika06** [comment]
From Your class, where you have create Custom maps Object.

**Comment by Bhoomika06** [comment]
OKay, Great! :)
